name: 'Hello アクション'
description: '誰かに挨拶をして、その時間を返す'
inputs:
  who-to-greet:
    description: '誰に挨拶するか'
    required: true
outputs:
  who-was-greeted:
    description: '誰に挨拶したか、敬称付きで返す'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
